default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: db


development:
  <<: *default
  database: taskflow_api_development


test:
  <<: *default
  database: taskflow_api_test

production:
  production:
    url: <%= ENV['DATABASE_URL'] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>