default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: db

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: taskflow_api_development


test:
  <<: *default
  database: taskflow_api_test

production:
  primary: &primary_production
    <<: *default
    database: taskflow_api_production
    username: taskflow_api
    password: <%= ENV["TASKFLOW_API_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: taskflow_api_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: taskflow_api_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: taskflow_api_production_cable
    migrations_paths: db/cable_migrate
